@startuml

header Dance-school
footer Nicola Iacovelli

actor Client
title Aggiungi Studente sequence diagram

== Login ==
Client -> LoginController: Authentication Request
Client <-- LoginController: Authentication Response

== Aggiungi studente ==
Client -> AlunnoController: PUT /student/
activate AlunnoController
AlunnoController -> AlunnoProxy: alunnoProxy.addStudent(student)
activate AlunnoProxy
AlunnoProxy -> AlunnoService: alunnoService.addStudent(student)
activate AlunnoService
AlunnoService -> AlunnoRepository: alunnoRepository.save(student)
activate AlunnoRepository
database DB
AlunnoRepository -> DB: Save entity
AlunnoRepository <- DB: Entity detached
return Entity detached
return Entity detached
return Entity id
return HTTP_STATUS.CREATED

== Logout ==
Client -> LoginController: Logout Request
Client <-- LoginController: Logout Response

@enduml