package it.iacovelli.danceschool.model

import java.io.Serializable
import java.util.*
import javax.persistence.*

/**
 * This is the model of Corso
 * @version 1.1
 * @author nicola.iacovelli
 */
@Entity
class Corso : Serializable {

    /**
     * This is the primary key of Corso entity and it's autogenerated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long = 0

    /**
     * This flag represents if the course is still active
     */
    var active: Boolean = false

    /**
     * This field represents the name of the course, its max length is 100 character
     */
    @Column(name = "name", length = 100)
    var name: String? = null

    /**
     * This field represents the description of the course
     */
    var description: String? = null

    /**
     * This list contains the students enrolled in the course
     */
    @OneToMany(mappedBy = "course")
    var subscribers: List<Iscrizione> = ArrayList()

    @ManyToOne
    @JoinColumn(name = "teacher")
    var teacher: Insegnante? = null

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Corso) return false

        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int {
        return id.hashCode()
    }

    override fun toString(): String {
        return "Corso(id=$id, isActive=$active, name=$name, description=$description, teacher=$teacher)"
    }

}
