package it.iacovelli.danceschool.model

import java.io.Serializable
import java.time.LocalDate
import javax.persistence.*

/**
 * This is the linking relation between [Alunno] and [Corso]
 * @version 1.0
 * @author nicola.iacovelli
 */
@Entity
class Iscrizione : Serializable {

    /**
     * This is the primary key of Iscrizione entity and it's autogenerated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long = 0

    /**
     * This field represent when the student was enrolled in the course
     */
    @Column(name = "subscribe_date", columnDefinition = "DATE")
    var subscribeDate: LocalDate? = null

    /**
     * This field represent the student enrolled
     */
    @ManyToOne
    @JoinColumn(name = "student")
    var student: Alunno? = null

    /**
     * This field represent the course to subscribe in
     */
    @ManyToOne
    @JoinColumn(name = "course")
    var course: Corso? = null

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Iscrizione) return false

        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int {
        return id.hashCode()
    }

    override fun toString(): String {
        return "Iscrizione(id=$id, subscribeDate=$subscribeDate, student=$student, course=$course)"
    }

}
